@startuml カレーライス
title カレーライスの作り方
start
:カレーライスを作る;
fork
    :鶏肉を切る;
    :人参を切る;
    :じゃがいもを切る;
    :玉ねぎを切る;
    :肉をあらかた炒める;
    :鍋に入れ、具材が浸るくらいの水を入れる;
    :ある程度煮えたらルーを入れ再び煮込む;
fork again
    :米を研ぎ、炊く;
end fork
:よそって完成;
stop
@enduml