@startuml
left to right direction
object "<u>A: 利用者クラス</u>" as k0 {
チェックイン日：五月三日
}
object "<u>B: 利用者クラス</u>" as k1 {
チェックイン日：五月三日
}
object "<u>301: 部屋クラス</u>" as k2 {
タイプ：シングル
宿泊料:11,000
キャンペーン価格:9,000

}
object "<u>302: 部屋クラス</u>" as k4 {
    タイプ：シングル
宿泊料:11,000
キャンペーン価格:9,000
}
object "<u>303: 部屋クラス</u>" as k3 {
    タイプ：シングル
宿泊料:11,000
キャンペーン価格:9,000
}
k0--k2
k1--k3