@startuml
left to right direction
state 電源SWON {
右旋回 --> 左旋回 : ラインを外れる(光センサーが明るい)
右旋回 : 右モータ = OFF
右旋回 : 左モータ = ON
左旋回 --> 右旋回 : ラインに乗る(光センサーが暗い)
左旋回 : 右モータ = ON
左旋回 : 左モータ = OFF
}
電源SWOFF --> 電源SWON: スイッチON
電源SWON --> 電源SWOFF: スイッチOFF
@enduml