@startuml
hide footbox
Actor ":会員" as m
participant ":注文登録画面" as r <<boundary>>
participant ":商品" as m2 <<entity>>
participant ":注文" as o <<entity>>
activate m
m -> r:商品情報確認（）
    activate r
    r -> m2:商品情報取得（）
    activate m2
    m2 -->> r:商品情報
     deactivate m2
    r -> r:商品情報表示（商品情報）
     activate r
     deactivate r
    deactivate r
    m -> r : 商品登録（注文情報）
    activate r
    create o
    r -->> o:生成する()<<create>>
   
@enduml