@startuml 演習2-1
left to right direction
actor 申請者 as u1 user #DDDDDD;line:black;line.bold;
actor 承認者 as u2 admin #DDDDDD;line:black;line.bold;
actor 経理担当者 as u3 admin #DDDDDD;line:black;line.bold;
actor 交通費精算システム as u4 #DDDDDD;line:black;line.bold;
rectangle 出張申請システム {
usecase 出張申請を登録する as 1
usecase 出張申請を提出する as 2
usecase 出張申請を承認する as 3
usecase 出張申請を却下する as 4
usecase 出張申請を差し戻す as 5
usecase 出張申請を確認する as 6
u1-->1
u1-->2
u2-->3
u2-->4
u2-->5
u2-->6
u3-->6
1<--u4
}
@enduml