@startuml
left to right direction
object "<u>高橋洋平さん:重要顧客</u>" as k1 {

}

object "<u>注文:注文クラス</u>" as k2{
}
object "<u>高田利恵:重要顧客</u>" as k3 {

}
object "<u>大坪直之:重要顧客</u>" as k4{

}
object "<u>テレビ:商品</u>" as k5{
    型式V12345   
}
object "<u>冷蔵庫:商品</u>" as k6{
    型式R8765
}
object "<u>プロジェクター:商品</u>" as k7{   
    型式P1122
}


k1--k2
k3--k2
k2--k5
k2--k6
@enduml